<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="del1-lhp-n65294" ignored="0" name="Test" tests="7" failures="5" timestamp="02 Aug 2019 11:24:27 GMT" time="64.22" errors="0">
  <testcase name="set_data_function" time="1.537" classname="satyam.mandal.testng.Before_After_annotation"/>
  <testcase name="set_data_function2" time="1.26" classname="satyam.mandal.testng.Before_After_annotation">
    <failure type="java.lang.AssertionError" message="expected [The credentials provided are incorrect] but found [checklist@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [The credentials provided are incorrect] but found [checklist@gmail.com]
at satyam.mandal.testng.Before_After_annotation.set_data_function2(Before_After_annotation.java:39)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- set_data_function2 -->
  <testcase name="set_data_function3" time="0.858" classname="satyam.mandal.testng.Before_After_annotation">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Please enter a valid email address.] but found [cbin$#12.com]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Please enter a valid email address.] but found [cbin$#12.com]
at satyam.mandal.testng.Before_After_annotation.set_data_function3(Before_After_annotation.java:53)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- set_data_function3 -->
  <testcase name="set_data_function4" time="1.7" classname="satyam.mandal.testng.Before_After_annotation">
    <failure type="java.lang.AssertionError" message="expected [No customer account found] but found [temp11@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [No customer account found] but found [temp11@gmail.com]
at satyam.mandal.testng.Before_After_annotation.set_data_function4(Before_After_annotation.java:63)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- set_data_function4 -->
  <testcase name="set_data_function5" time="1.072" classname="satyam.mandal.testng.Before_After_annotation">
    <failure type="java.lang.AssertionError" message="expected [No customer account found] but found []">
      <![CDATA[java.lang.AssertionError: expected [No customer account found] but found []
at satyam.mandal.testng.Before_After_annotation.set_data_function5(Before_After_annotation.java:73)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- set_data_function5 -->
  <testcase name="f1" time="8.39" classname="satyam.mandal.testng.excel_test">
    <failure type="java.lang.AssertionError" message="expected [mandal0927@gmail.com] but found [mandalsatyam333@gmail.com]">
      <![CDATA[java.lang.AssertionError: expected [mandal0927@gmail.com] but found [mandalsatyam333@gmail.com]
at satyam.mandal.testng.Login_function.login1(Login_function.java:44)
at satyam.mandal.testng.excel_test.f1(excel_test.java:8)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f2" time="10.27" classname="satyam.mandal.testng.excel_test"/>
</testsuite> <!-- Test -->
